[package]
name = "cube"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
rand = "0.8.5"
ratatui = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
unicode-segmentation = "1.11.0"
